-- +goose Up
-- +goose StatementBegin
CREATE TABLE movie (
    id bigint generated by default as identity,
    created_date timestamp(6) with time zone not null,
    modified_date timestamp(6) with time zone not null,
    available_globally boolean,
    locale varchar(10),
    original_title varchar(255),
    release_date date,
    runtime bigint,
    title varchar(255) not null,
    primary key (id)
);

COMMENT ON COLUMN movie.id IS 'Primary unique identifier';
COMMENT ON COLUMN movie.created_date IS 'Date when this record was created';
COMMENT ON COLUMN movie.modified_date IS 'Date when this record was last modified';
COMMENT ON COLUMN movie.available_globally IS 'A flag that indicates if this title is available outside US';
COMMENT ON COLUMN movie.locale IS 'The original language/region of the movie';
COMMENT ON COLUMN movie.original_title IS 'The movie title in its original language';
COMMENT ON COLUMN movie.release_date IS 'Date when this title was released';
COMMENT ON COLUMN movie.runtime IS 'The total runtime in minutes';
COMMENT ON COLUMN movie.title IS 'The movie title';

CREATE TABLE season (
    id bigint generated by default as identity,
    created_date timestamp(6) with time zone not null,
    modified_date timestamp(6) with time zone not null,
    original_title varchar(255),
    release_date date,
    runtime bigint,
    season_number integer,
    title varchar(255) not null,
    tv_show_id bigint,
    primary key (id)
);

COMMENT ON COLUMN season.id IS 'Primary unique identifier';
COMMENT ON COLUMN season.created_date IS 'Date when this record was created';
COMMENT ON COLUMN season.modified_date IS 'Date when this record was last modified';
COMMENT ON COLUMN season.original_title IS 'The season title in its original language';
COMMENT ON COLUMN season.release_date IS 'Date when this title was released';
COMMENT ON COLUMN season.runtime IS 'The total runtime in minutes';
COMMENT ON COLUMN season.season_number IS 'The season number';
COMMENT ON COLUMN season.title IS 'The season title';
COMMENT ON COLUMN season.tv_show_id IS 'The TV show that this season belongs to';

CREATE TABLE tv_show (
    id bigint generated by default as identity,
    created_date timestamp(6) with time zone not null,
    modified_date timestamp(6) with time zone not null,
    available_globally boolean,
    locale varchar(10),
    original_title varchar(255),
    release_date date,
    title varchar(255) not null,
    primary key (id),
    constraint idx_tv_show_title unique (title)
);

COMMENT ON COLUMN tv_show.id IS 'Primary unique identifier';
COMMENT ON COLUMN tv_show.created_date IS 'Date when this record was created';
COMMENT ON COLUMN tv_show.modified_date IS 'Date when this record was last modified';
COMMENT ON COLUMN tv_show.available_globally IS 'A flag that indicates if this title is available outside US';
COMMENT ON COLUMN tv_show.locale IS 'The original language/region of the TV show';
COMMENT ON COLUMN tv_show.original_title IS 'The TV show title in its original language';
COMMENT ON COLUMN tv_show.release_date IS 'Date when this title was released';
COMMENT ON COLUMN tv_show.title IS 'The TV show title';

CREATE TABLE view_summary (
    id bigint generated by default as identity,
    created_date timestamp(6) with time zone not null,
    modified_date timestamp(6) with time zone not null,
    cumulative_weeks_in_top10 integer,
    duration varchar(20) not null check (duration in ('WEEKLY','SEMI_ANNUALLY')),
    end_date date not null,
    hours_viewed integer not null,
    start_date date not null,
    view_rank integer,
    views integer,
    movie_id bigint,
    season_id bigint,
    primary key (id)
);

COMMENT ON COLUMN view_summary.id IS 'Primary unique identifier';
COMMENT ON COLUMN view_summary.created_date IS 'Date when this record was created';
COMMENT ON COLUMN view_summary.modified_date IS 'Date when this record was last modified';
COMMENT ON COLUMN view_summary.cumulative_weeks_in_top10 IS 'The number of cumulative weeks in top 10 list';
COMMENT ON COLUMN view_summary.duration IS 'The duration of the period this summary refers to';
COMMENT ON COLUMN view_summary.end_date IS 'The last day of the period this summary refers to';
COMMENT ON COLUMN view_summary.hours_viewed IS 'The total hours viewed during this period';
COMMENT ON COLUMN view_summary.start_date IS 'The first day of the period this summary refers to';
COMMENT ON COLUMN view_summary.view_rank IS 'The rank during this period';
COMMENT ON COLUMN view_summary.views IS 'The number of views during this period';
COMMENT ON COLUMN view_summary.movie_id IS 'The movie for this weekly summary';
COMMENT ON COLUMN view_summary.season_id IS 'The season for this weekly summary';

CREATE INDEX idx_movie_title_runtime ON movie (title, runtime);
CREATE INDEX idx_season_title_runtime ON season (title, runtime);
CREATE INDEX fk_season_tv_show_id ON season (tv_show_id);

ALTER TABLE IF EXISTS season 
   ADD CONSTRAINT fk_season_tv_show_id 
   FOREIGN KEY (tv_show_id) 
   REFERENCES tv_show;

ALTER TABLE IF EXISTS view_summary 
   ADD CONSTRAINT fk_view_summary_movie_id 
   FOREIGN KEY (movie_id) 
   REFERENCES movie;

ALTER TABLE IF EXISTS view_summary 
   ADD CONSTRAINT fk_view_summary_season_id 
   FOREIGN KEY (season_id) 
   REFERENCES season;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS view_summary;
DROP TABLE IF EXISTS season;
DROP TABLE IF EXISTS tv_show;
DROP TABLE IF EXISTS movie;
-- +goose StatementEnd
