// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/amit/gin-crud-demo/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockViewSummaryRepository is an autogenerated mock type for the ViewSummaryRepository type
type MockViewSummaryRepository struct {
	mock.Mock
}

type MockViewSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViewSummaryRepository) EXPECT() *MockViewSummaryRepository_Expecter {
	return &MockViewSummaryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, summary
func (_m *MockViewSummaryRepository) Create(ctx context.Context, summary *models.ViewSummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ViewSummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewSummaryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockViewSummaryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *models.ViewSummary
func (_e *MockViewSummaryRepository_Expecter) Create(ctx interface{}, summary interface{}) *MockViewSummaryRepository_Create_Call {
	return &MockViewSummaryRepository_Create_Call{Call: _e.mock.On("Create", ctx, summary)}
}

func (_c *MockViewSummaryRepository_Create_Call) Run(run func(ctx context.Context, summary *models.ViewSummary)) *MockViewSummaryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ViewSummary))
	})
	return _c
}

func (_c *MockViewSummaryRepository_Create_Call) Return(_a0 error) *MockViewSummaryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewSummaryRepository_Create_Call) RunAndReturn(run func(context.Context, *models.ViewSummary) error) *MockViewSummaryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockViewSummaryRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewSummaryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockViewSummaryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockViewSummaryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockViewSummaryRepository_Delete_Call {
	return &MockViewSummaryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockViewSummaryRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockViewSummaryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockViewSummaryRepository_Delete_Call) Return(_a0 error) *MockViewSummaryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewSummaryRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockViewSummaryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockViewSummaryRepository) GetByID(ctx context.Context, id int64) (*models.ViewSummary, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.ViewSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.ViewSummary, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.ViewSummary); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ViewSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockViewSummaryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockViewSummaryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockViewSummaryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockViewSummaryRepository_GetByID_Call {
	return &MockViewSummaryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockViewSummaryRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockViewSummaryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockViewSummaryRepository_GetByID_Call) Return(_a0 *models.ViewSummary, _a1 error) *MockViewSummaryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockViewSummaryRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.ViewSummary, error)) *MockViewSummaryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *MockViewSummaryRepository) List(ctx context.Context, page int, limit int) ([]models.ViewSummary, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.ViewSummary
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.ViewSummary, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.ViewSummary); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ViewSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockViewSummaryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockViewSummaryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockViewSummaryRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockViewSummaryRepository_List_Call {
	return &MockViewSummaryRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockViewSummaryRepository_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockViewSummaryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockViewSummaryRepository_List_Call) Return(_a0 []models.ViewSummary, _a1 int64, _a2 error) *MockViewSummaryRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockViewSummaryRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]models.ViewSummary, int64, error)) *MockViewSummaryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, summary
func (_m *MockViewSummaryRepository) Update(ctx context.Context, summary *models.ViewSummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ViewSummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewSummaryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockViewSummaryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *models.ViewSummary
func (_e *MockViewSummaryRepository_Expecter) Update(ctx interface{}, summary interface{}) *MockViewSummaryRepository_Update_Call {
	return &MockViewSummaryRepository_Update_Call{Call: _e.mock.On("Update", ctx, summary)}
}

func (_c *MockViewSummaryRepository_Update_Call) Run(run func(ctx context.Context, summary *models.ViewSummary)) *MockViewSummaryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ViewSummary))
	})
	return _c
}

func (_c *MockViewSummaryRepository_Update_Call) Return(_a0 error) *MockViewSummaryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewSummaryRepository_Update_Call) RunAndReturn(run func(context.Context, *models.ViewSummary) error) *MockViewSummaryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockViewSummaryRepository creates a new instance of MockViewSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViewSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViewSummaryRepository {
	mock := &MockViewSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
