// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/amit/gin-crud-demo/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTVShowRepository is an autogenerated mock type for the TVShowRepository type
type MockTVShowRepository struct {
	mock.Mock
}

type MockTVShowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTVShowRepository) EXPECT() *MockTVShowRepository_Expecter {
	return &MockTVShowRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tvShow
func (_m *MockTVShowRepository) Create(ctx context.Context, tvShow *models.TVShow) error {
	ret := _m.Called(ctx, tvShow)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TVShow) error); ok {
		r0 = rf(ctx, tvShow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTVShowRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTVShowRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tvShow *models.TVShow
func (_e *MockTVShowRepository_Expecter) Create(ctx interface{}, tvShow interface{}) *MockTVShowRepository_Create_Call {
	return &MockTVShowRepository_Create_Call{Call: _e.mock.On("Create", ctx, tvShow)}
}

func (_c *MockTVShowRepository_Create_Call) Run(run func(ctx context.Context, tvShow *models.TVShow)) *MockTVShowRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.TVShow))
	})
	return _c
}

func (_c *MockTVShowRepository_Create_Call) Return(_a0 error) *MockTVShowRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTVShowRepository_Create_Call) RunAndReturn(run func(context.Context, *models.TVShow) error) *MockTVShowRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTVShowRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTVShowRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTVShowRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTVShowRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTVShowRepository_Delete_Call {
	return &MockTVShowRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTVShowRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockTVShowRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTVShowRepository_Delete_Call) Return(_a0 error) *MockTVShowRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTVShowRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockTVShowRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTVShowRepository) GetByID(ctx context.Context, id int64) (*models.TVShow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.TVShow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.TVShow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.TVShow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TVShow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTVShowRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTVShowRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTVShowRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTVShowRepository_GetByID_Call {
	return &MockTVShowRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTVShowRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTVShowRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTVShowRepository_GetByID_Call) Return(_a0 *models.TVShow, _a1 error) *MockTVShowRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTVShowRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.TVShow, error)) *MockTVShowRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *MockTVShowRepository) List(ctx context.Context, page int, limit int) ([]models.TVShow, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.TVShow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.TVShow, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.TVShow); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TVShow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTVShowRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTVShowRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockTVShowRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockTVShowRepository_List_Call {
	return &MockTVShowRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockTVShowRepository_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockTVShowRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTVShowRepository_List_Call) Return(_a0 []models.TVShow, _a1 int64, _a2 error) *MockTVShowRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTVShowRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]models.TVShow, int64, error)) *MockTVShowRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tvShow
func (_m *MockTVShowRepository) Update(ctx context.Context, tvShow *models.TVShow) error {
	ret := _m.Called(ctx, tvShow)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TVShow) error); ok {
		r0 = rf(ctx, tvShow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTVShowRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTVShowRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tvShow *models.TVShow
func (_e *MockTVShowRepository_Expecter) Update(ctx interface{}, tvShow interface{}) *MockTVShowRepository_Update_Call {
	return &MockTVShowRepository_Update_Call{Call: _e.mock.On("Update", ctx, tvShow)}
}

func (_c *MockTVShowRepository_Update_Call) Run(run func(ctx context.Context, tvShow *models.TVShow)) *MockTVShowRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.TVShow))
	})
	return _c
}

func (_c *MockTVShowRepository_Update_Call) Return(_a0 error) *MockTVShowRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTVShowRepository_Update_Call) RunAndReturn(run func(context.Context, *models.TVShow) error) *MockTVShowRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTVShowRepository creates a new instance of MockTVShowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTVShowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTVShowRepository {
	mock := &MockTVShowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
