// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/amit/gin-crud-demo/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSeasonRepository is an autogenerated mock type for the SeasonRepository type
type MockSeasonRepository struct {
	mock.Mock
}

type MockSeasonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeasonRepository) EXPECT() *MockSeasonRepository_Expecter {
	return &MockSeasonRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, season
func (_m *MockSeasonRepository) Create(ctx context.Context, season *models.Season) error {
	ret := _m.Called(ctx, season)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Season) error); ok {
		r0 = rf(ctx, season)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeasonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSeasonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - season *models.Season
func (_e *MockSeasonRepository_Expecter) Create(ctx interface{}, season interface{}) *MockSeasonRepository_Create_Call {
	return &MockSeasonRepository_Create_Call{Call: _e.mock.On("Create", ctx, season)}
}

func (_c *MockSeasonRepository_Create_Call) Run(run func(ctx context.Context, season *models.Season)) *MockSeasonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Season))
	})
	return _c
}

func (_c *MockSeasonRepository_Create_Call) Return(_a0 error) *MockSeasonRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeasonRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Season) error) *MockSeasonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSeasonRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeasonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSeasonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockSeasonRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSeasonRepository_Delete_Call {
	return &MockSeasonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSeasonRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockSeasonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockSeasonRepository_Delete_Call) Return(_a0 error) *MockSeasonRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeasonRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockSeasonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSeasonRepository) GetByID(ctx context.Context, id int64) (*models.Season, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Season
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Season, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Season); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Season)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeasonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSeasonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockSeasonRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSeasonRepository_GetByID_Call {
	return &MockSeasonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSeasonRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockSeasonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockSeasonRepository_GetByID_Call) Return(_a0 *models.Season, _a1 error) *MockSeasonRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeasonRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Season, error)) *MockSeasonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *MockSeasonRepository) List(ctx context.Context, page int, limit int) ([]models.Season, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Season
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Season, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Season); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Season)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSeasonRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSeasonRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockSeasonRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockSeasonRepository_List_Call {
	return &MockSeasonRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockSeasonRepository_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockSeasonRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSeasonRepository_List_Call) Return(_a0 []models.Season, _a1 int64, _a2 error) *MockSeasonRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSeasonRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Season, int64, error)) *MockSeasonRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, season
func (_m *MockSeasonRepository) Update(ctx context.Context, season *models.Season) error {
	ret := _m.Called(ctx, season)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Season) error); ok {
		r0 = rf(ctx, season)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeasonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSeasonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - season *models.Season
func (_e *MockSeasonRepository_Expecter) Update(ctx interface{}, season interface{}) *MockSeasonRepository_Update_Call {
	return &MockSeasonRepository_Update_Call{Call: _e.mock.On("Update", ctx, season)}
}

func (_c *MockSeasonRepository_Update_Call) Run(run func(ctx context.Context, season *models.Season)) *MockSeasonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Season))
	})
	return _c
}

func (_c *MockSeasonRepository_Update_Call) Return(_a0 error) *MockSeasonRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeasonRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Season) error) *MockSeasonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeasonRepository creates a new instance of MockSeasonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeasonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeasonRepository {
	mock := &MockSeasonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
