// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/amit/gin-crud-demo/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockMovieRepository is an autogenerated mock type for the MovieRepository type
type MockMovieRepository struct {
	mock.Mock
}

type MockMovieRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieRepository) EXPECT() *MockMovieRepository_Expecter {
	return &MockMovieRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, movie
func (_m *MockMovieRepository) Create(ctx context.Context, movie *models.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMovieRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMovieRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
func (_e *MockMovieRepository_Expecter) Create(ctx interface{}, movie interface{}) *MockMovieRepository_Create_Call {
	return &MockMovieRepository_Create_Call{Call: _e.mock.On("Create", ctx, movie)}
}

func (_c *MockMovieRepository_Create_Call) Run(run func(ctx context.Context, movie *models.Movie)) *MockMovieRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Movie))
	})
	return _c
}

func (_c *MockMovieRepository_Create_Call) Return(_a0 error) *MockMovieRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMovieRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Movie) error) *MockMovieRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMovieRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMovieRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMovieRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMovieRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMovieRepository_Delete_Call {
	return &MockMovieRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMovieRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockMovieRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMovieRepository_Delete_Call) Return(_a0 error) *MockMovieRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMovieRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockMovieRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMovieRepository) GetByID(ctx context.Context, id int64) (*models.Movie, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Movie, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMovieRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMovieRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMovieRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMovieRepository_GetByID_Call {
	return &MockMovieRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMovieRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockMovieRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMovieRepository_GetByID_Call) Return(_a0 *models.Movie, _a1 error) *MockMovieRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMovieRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Movie, error)) *MockMovieRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *MockMovieRepository) List(ctx context.Context, page int, limit int) ([]models.Movie, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Movie
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Movie, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Movie); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMovieRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMovieRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockMovieRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockMovieRepository_List_Call {
	return &MockMovieRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockMovieRepository_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockMovieRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockMovieRepository_List_Call) Return(_a0 []models.Movie, _a1 int64, _a2 error) *MockMovieRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMovieRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Movie, int64, error)) *MockMovieRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, movie
func (_m *MockMovieRepository) Update(ctx context.Context, movie *models.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMovieRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMovieRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
func (_e *MockMovieRepository_Expecter) Update(ctx interface{}, movie interface{}) *MockMovieRepository_Update_Call {
	return &MockMovieRepository_Update_Call{Call: _e.mock.On("Update", ctx, movie)}
}

func (_c *MockMovieRepository_Update_Call) Run(run func(ctx context.Context, movie *models.Movie)) *MockMovieRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Movie))
	})
	return _c
}

func (_c *MockMovieRepository_Update_Call) Return(_a0 error) *MockMovieRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMovieRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Movie) error) *MockMovieRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMovieRepository creates a new instance of MockMovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieRepository {
	mock := &MockMovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
